### ISSUE TITLE
在vercel中部署后,二维码不显示，只有空白框

### ISSUE THREAD

**Issue by Troray** [itxve/aliyundriver-refresh-token#4]
在推荐的vercel中部署后，网页上的二维码不显示，只有一个空白的框。
部署时的框架选了默认的那个vite。不知道是哪边的问题了。能否解惑一下？
在自己的vps上也是不显示二维码，只有空白框及“请用阿里云盘 App 扫码”几个字。
[地址在这里](https://aliyundriver-refresh-token-five.vercel.app)

```
--
00:39:01.720 | Cloning completed: 433.387ms
00:39:01.875 | Running "vercel build"
00:39:02.448 | Vercel CLI 28.13.2
00:39:03.590 | Running "install" command: `npm install`...
00:39:08.373 |  
00:39:08.374 | added 58 packages, and audited 59 packages in 4s
00:39:08.374 |  
00:39:08.374 | 6 packages are looking for funding
00:39:08.374 | run `npm fund` for details
00:39:08.375 |  
00:39:08.375 | found 0 vulnerabilities
00:39:08.394 | Detected `package-lock.json` generated by npm 7+...
00:39:08.395 | Running "npm run build"
00:39:08.797 |  
00:39:08.797 | > aliyundrive-refresh-token@1.0.0 build
00:39:08.798 | > tsc --noEmit && vite build
00:39:08.798 |  
00:39:10.717 | vite v2.9.15 building for production...
00:39:10.790 | transforming...
00:39:10.860 | ✓ 4 modules transformed.
00:39:10.882 | rendering chunks...
00:39:10.889 | dist/index.html                 1.85 KiB
00:39:10.891 | dist/assets/index.06776baa.js   1.83 KiB / gzip: 0.89 KiB
00:39:10.931 | Installing dependencies...
00:39:11.621 |  
00:39:11.621 | up to date in 323ms
00:39:11.622 |  
00:39:11.622 | 6 packages are looking for funding
00:39:11.622 | run `npm fund` for details
00:39:11.960 | Using TypeScript 4.9.4 (local user-provided)
00:39:14.192 | Using TypeScript 4.9.4 (local user-provided)
00:39:14.313 | Build Completed in /vercel/output [11s]
00:39:17.147 | Generated build outputs:
00:39:17.147 | - Static files: 4
00:39:17.147 | - Serverless Functions: 2
00:39:17.147 | - Edge Functions: 0
00:39:17.148 | Serverless regions: Washington, D.C., USA
00:39:17.148 | Deployed outputs in 2s
00:39:17.864 | Build completed. Populating build cache...
00:39:20.666 | Uploading build cache [11.00 MB]...
00:39:21.908 | Build cache uploaded: 1.243s

```

**Comment by itxve** [comment]
重新部署下项目即可

**Comment by itxve** [comment]
> 在推荐的vercel中部署后，网页上的二维码不显示，只有一个空白的框。 部署时的框架选了默认的那个vite。不知道是哪边的问题了。能否解惑一下？ 在自己的vps上也是不显示二维码，只有空白框及“请用阿里云盘 App 扫码”几个字。 [地址在这里](https://aliyundriver-refresh-token-five.vercel.app)
> 
> ```
> --
> 00:39:01.720 | Cloning completed: 433.387ms
> 00:39:01.875 | Running "vercel build"
> 00:39:02.448 | Vercel CLI 28.13.2
> 00:39:03.590 | Running "install" command: `npm install`...
> 00:39:08.373 |  
> 00:39:08.374 | added 58 packages, and audited 59 packages in 4s
> 00:39:08.374 |  
> 00:39:08.374 | 6 packages are looking for funding
> 00:39:08.374 | run `npm fund` for details
> 00:39:08.375 |  
> 00:39:08.375 | found 0 vulnerabilities
> 00:39:08.394 | Detected `package-lock.json` generated by npm 7+...
> 00:39:08.395 | Running "npm run build"
> 00:39:08.797 |  
> 00:39:08.797 | > aliyundrive-refresh-token@1.0.0 build
> 00:39:08.798 | > tsc --noEmit && vite build
> 00:39:08.798 |  
> 00:39:10.717 | vite v2.9.15 building for production...
> 00:39:10.790 | transforming...
> 00:39:10.860 | ✓ 4 modules transformed.
> 00:39:10.882 | rendering chunks...
> 00:39:10.889 | dist/index.html                 1.85 KiB
> 00:39:10.891 | dist/assets/index.06776baa.js   1.83 KiB / gzip: 0.89 KiB
> 00:39:10.931 | Installing dependencies...
> 00:39:11.621 |  
> 00:39:11.621 | up to date in 323ms
> 00:39:11.622 |  
> 00:39:11.622 | 6 packages are looking for funding
> 00:39:11.622 | run `npm fund` for details
> 00:39:11.960 | Using TypeScript 4.9.4 (local user-provided)
> 00:39:14.192 | Using TypeScript 4.9.4 (local user-provided)
> 00:39:14.313 | Build Completed in /vercel/output [11s]
> 00:39:17.147 | Generated build outputs:
> 00:39:17.147 | - Static files: 4
> 00:39:17.147 | - Serverless Functions: 2
> 00:39:17.147 | - Edge Functions: 0
> 00:39:17.148 | Serverless regions: Washington, D.C., USA
> 00:39:17.148 | Deployed outputs in 2s
> 00:39:17.864 | Build completed. Populating build cache...
> 00:39:20.666 | Uploading build cache [11.00 MB]...
> 00:39:21.908 | Build cache uploaded: 1.243s
> ```
重新部署下项目，问题已修复
手段有点暴力，哈哈。
我猜是ts版本导致的，原先并没有使用 "type": "module"是编译pass的。

**Comment by Troray** [comment]
> > 在推荐的vercel中部署后，网页上的二维码不显示，只有一个空白的框。 部署时的框架选了默认的那个vite。不知道是哪边的问题了。能否解惑一下？ 在自己的vps上也是不显示二维码，只有空白框及“请用阿里云盘 App 扫码”几个字。 [地址在这里](https://aliyundriver-refresh-token-five.vercel.app)
> > ```
> > --
> > 00:39:01.720 | Cloning completed: 433.387ms
> > 00:39:01.875 | Running "vercel build"
> > 00:39:02.448 | Vercel CLI 28.13.2
> > 00:39:03.590 | Running "install" command: `npm install`...
> > 00:39:08.373 |  
> > 00:39:08.374 | added 58 packages, and audited 59 packages in 4s
> > 00:39:08.374 |  
> > 00:39:08.374 | 6 packages are looking for funding
> > 00:39:08.374 | run `npm fund` for details
> > 00:39:08.375 |  
> > 00:39:08.375 | found 0 vulnerabilities
> > 00:39:08.394 | Detected `package-lock.json` generated by npm 7+...
> > 00:39:08.395 | Running "npm run build"
> > 00:39:08.797 |  
> > 00:39:08.797 | > aliyundrive-refresh-token@1.0.0 build
> > 00:39:08.798 | > tsc --noEmit && vite build
> > 00:39:08.798 |  
> > 00:39:10.717 | vite v2.9.15 building for production...
> > 00:39:10.790 | transforming...
> > 00:39:10.860 | ✓ 4 modules transformed.
> > 00:39:10.882 | rendering chunks...
> > 00:39:10.889 | dist/index.html                 1.85 KiB
> > 00:39:10.891 | dist/assets/index.06776baa.js   1.83 KiB / gzip: 0.89 KiB
> > 00:39:10.931 | Installing dependencies...
> > 00:39:11.621 |  
> > 00:39:11.621 | up to date in 323ms
> > 00:39:11.622 |  
> > 00:39:11.622 | 6 packages are looking for funding
> > 00:39:11.622 | run `npm fund` for details
> > 00:39:11.960 | Using TypeScript 4.9.4 (local user-provided)
> > 00:39:14.192 | Using TypeScript 4.9.4 (local user-provided)
> > 00:39:14.313 | Build Completed in /vercel/output [11s]
> > 00:39:17.147 | Generated build outputs:
> > 00:39:17.147 | - Static files: 4
> > 00:39:17.147 | - Serverless Functions: 2
> > 00:39:17.147 | - Edge Functions: 0
> > 00:39:17.148 | Serverless regions: Washington, D.C., USA
> > 00:39:17.148 | Deployed outputs in 2s
> > 00:39:17.864 | Build completed. Populating build cache...
> > 00:39:20.666 | Uploading build cache [11.00 MB]...
> > 00:39:21.908 | Build cache uploaded: 1.243s
> > ```
> 
> 重新部署下项目，问题已修复 手段有点暴力，哈哈。 我猜是ts版本导致的，原先并没有使用 "type": "module"是编译pass的。

ok,重新部署后可以了。
但是输出的信息有点多啊，我的建议是可以仅显示头像，用户名和refreshToken字段信息。
另外，感谢提供程序！

**Comment by itxve** [comment]
> > > 在推荐的vercel中部署后，网页上的二维码不显示，只有一个空白的框。 部署时的框架选了默认的那个vite。不知道是哪边的问题了。能否解惑一下？ 在自己的vps上也是不显示二维码，只有空白框及“请用阿里云盘 App 扫码”几个字。 [地址在这里](https://aliyundriver-refresh-token-five.vercel.app)
> > > ```
> > > --
> > > 00:39:01.720 | Cloning completed: 433.387ms
> > > 00:39:01.875 | Running "vercel build"
> > > 00:39:02.448 | Vercel CLI 28.13.2
> > > 00:39:03.590 | Running "install" command: `npm install`...
> > > 00:39:08.373 |  
> > > 00:39:08.374 | added 58 packages, and audited 59 packages in 4s
> > > 00:39:08.374 |  
> > > 00:39:08.374 | 6 packages are looking for funding
> > > 00:39:08.374 | run `npm fund` for details
> > > 00:39:08.375 |  
> > > 00:39:08.375 | found 0 vulnerabilities
> > > 00:39:08.394 | Detected `package-lock.json` generated by npm 7+...
> > > 00:39:08.395 | Running "npm run build"
> > > 00:39:08.797 |  
> > > 00:39:08.797 | > aliyundrive-refresh-token@1.0.0 build
> > > 00:39:08.798 | > tsc --noEmit && vite build
> > > 00:39:08.798 |  
> > > 00:39:10.717 | vite v2.9.15 building for production...
> > > 00:39:10.790 | transforming...
> > > 00:39:10.860 | ✓ 4 modules transformed.
> > > 00:39:10.882 | rendering chunks...
> > > 00:39:10.889 | dist/index.html                 1.85 KiB
> > > 00:39:10.891 | dist/assets/index.06776baa.js   1.83 KiB / gzip: 0.89 KiB
> > > 00:39:10.931 | Installing dependencies...
> > > 00:39:11.621 |  
> > > 00:39:11.621 | up to date in 323ms
> > > 00:39:11.622 |  
> > > 00:39:11.622 | 6 packages are looking for funding
> > > 00:39:11.622 | run `npm fund` for details
> > > 00:39:11.960 | Using TypeScript 4.9.4 (local user-provided)
> > > 00:39:14.192 | Using TypeScript 4.9.4 (local user-provided)
> > > 00:39:14.313 | Build Completed in /vercel/output [11s]
> > > 00:39:17.147 | Generated build outputs:
> > > 00:39:17.147 | - Static files: 4
> > > 00:39:17.147 | - Serverless Functions: 2
> > > 00:39:17.147 | - Edge Functions: 0
> > > 00:39:17.148 | Serverless regions: Washington, D.C., USA
> > > 00:39:17.148 | Deployed outputs in 2s
> > > 00:39:17.864 | Build completed. Populating build cache...
> > > 00:39:20.666 | Uploading build cache [11.00 MB]...
> > > 00:39:21.908 | Build cache uploaded: 1.243s
> > > ```
> > 
> > 
> > 重新部署下项目，问题已修复 手段有点暴力，哈哈。 我猜是ts版本导致的，原先并没有使用 "type": "module"是编译pass的。
> 
> ok,重新部署后可以了。 但是输出的信息有点多啊，我的建议是可以仅显示头像，用户名和refreshToken字段信息。 另外，感谢提供程序！

感谢建议，已采纳。
